export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'

export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR'

export const CHANGE_TEXT = 'CHANGE_TEXT'
export const TEXTFIELD_FOCUS_ON = 'TEXTFIELD_FOCUS_ON'
export const TEXTFIELD_FOCUS_OFF = 'TEXTFIELD_FOCUS_OFF'
export const SELECT_LIST_ITEM = 'SELECT_LIST_ITEM'
export const HOVER_LIST_ITEM = 'HOVER_LIST_ITEM'